language: c
services: docker
sudo: required
script:
  - "travis_wait 45 sleep 2700 &"
  - make build
after_script:
  - docker images
  - make docker-deploy
# deploy:
#   - provider: script
#     script: make docker-deploy
#     on:
#       branch:
#         - master
#         - devel
notifications:
  email:
    on_success: never
    on_failure: change
