language: c
services: docker
sudo: required
env: []
before_script: []
script:
  - make build
after_script:
  - docker images
deploy:
  - provider: script
    script: make docker-deploy
    on:
      branch:
        - master
        - devel
notifications:
  email:
    on_success: never
    on_failure: change
