FROM @IMAGE_BASE_NAME@:@VERSION@ as modtran


MAINTAINER USGS EROS LSRD http://eros.usgs.gov


LABEL description="This build adds in MODTRAN which we are not allowed to distribute."


# ----------------------------------------------------------------------------
# Actual image generation
FROM @IMAGE_SCIENCE_NAME@:@VERSION@


MAINTAINER USGS EROS LSRD http://eros.usgs.gov


LABEL description="This build adds in MODTRAN which we are not allowed to distribute."


# Copy the built executable from the intermediate image
COPY --from=modtran /usr/local/bin/mod53 /usr/local/bin/modtran
